setwd("/home/localadmin/project/ukbppp/data")
library("tidyverse")
data<-read.csv("UkbUnivariateDiseaseAssociations.csv")
data %>% filter(hazard_ratio>1)
data %>% filter(Assay=="MLKL")
data %>% filter(adjusted_pval<0.05) %>% filter(grepl("Epilepsy",phenotype) & hazard_ratio>1) %>% arrange(adjusted_pval) %>% head()
data %>% filter(adjusted_pval<0.05) %>% filter(grepl("obstructive",phenotype)) %>% arrange(adjusted_pval) %>% head()
data %>% filter(grepl("obstructive",phenotype)) %>% arrange(adjusted_pval) %>% head()


## epilepsy
library("openxlsx")
library("tidyverse")
library("easyPubMed")
library("data.table")
opentargets<-read_table("~/project/epilepsy/data/OT-EFO_0000474-associated-targets-5_10_2024-v24_03.tsv")
epidata2<-read.csv("~/project/epilepsy/gene-burden-results-exomes_pLoF_icd_first_occurrence-131048-both_sexes--_2024_03_08_16_15_09.csv") %>% select(Gene.Name,P.Value.Burden,BETA.Burden)
epidata3<-read.csv("~/project/epilepsy/gene-burden-results-exomes_pLoF_icd_first_occurrence-131050-both_sexes--_2024_03_08_16_57_00.csv")%>% select(Gene.Name,P.Value.Burden,BETA.Burden)
data<-left_join(opentargets,epidata2,by=c("symbol"="Gene.Name")) 
data<-left_join(data,epidata3,by=c("symbol"="Gene.Name")) %>% filter(BETA.Burden.x<0 & BETA.Burden.y<0) %>% select(symbol,globalScore,BETA.Burden.x,P.Value.Burden.x,BETA.Burden.y,P.Value.Burden.y)
tmp<-read.csv("~/project/ukbppp/data/UkbUnivariateDiseaseAssociations.csv") %>% filter(adjusted_pval<0.05) %>% filter(grepl("Epilepsy",phenotype) & hazard_ratio>1.5)
data<-inner_join(data,tmp,by=c("symbol"="Assay"))

## rheumatoid
library("openxlsx")
library("tidyverse")
library("easyPubMed")
library("data.table")
opentargets<-read_table("~/project/rheumatoid/data/OT-EFO_0000685-associated-targets-5_23_2024-v24_03.tsv")
epidata2<-read.csv("~/project/rheumatoid/data/gene-burden-results-exomes_pLoF_icd_first_occurrence-131848-both_sexes--_2024_05_13_10_27_36.csv") %>% select(Gene.Name,P.Value.Burden,BETA.Burden)
epidata3<-read.csv("~/project/rheumatoid/data/gene-burden-results-exomes_pLoF_icd_first_occurrence-131850-both_sexes--_2024_05_13_10_27_49.csv")%>% select(Gene.Name,P.Value.Burden,BETA.Burden)
data<-left_join(opentargets,epidata2,by=c("symbol"="Gene.Name")) 
data<-left_join(data,epidata3,by=c("symbol"="Gene.Name")) %>% filter(BETA.Burden.x<0 & BETA.Burden.y<0) %>% select(symbol,globalScore,BETA.Burden.x,P.Value.Burden.x,BETA.Burden.y,P.Value.Burden.y)
tmp<-read.csv("~/project/ukbppp/data/UkbUnivariateDiseaseAssociations.csv") %>% filter(adjusted_pval<0.05) %>% filter(grepl("Rheumatoid arthritis",phenotype) & hazard_ratio>1)
data<-inner_join(data,tmp,by=c("symbol"="Assay"))
write.xlsx(data,file="RA.xlsx")
